trigger: none

parameters:
- name: buildTargets # This list matches the variants we have templated in the .pipelines/vars/ directory. Additionally, buildTargets must follow the same naming conventions as stage id naming, this is because it is reused for uniquely identifying each buildTarget's stage. Valid names may only contain alphanumeric characters and '_'.
  type: object
  default:
    - 'uki'
    - 'azl3'

extends:
  template: az-sec.common-template.yml@self
  parameters:
    isOfficialPipeline: false
    buildTargets: ${{ parameters.buildTargets }}