# azure-pipelines.yml
trigger: none

pr:
  branches:
    include:
      - fasttrack/abadawi/test/3.0

name: Automaton-OpenAI-PR-Check

pool:
  name: mariner-dev-build-1es-mariner2-amd64

steps:
  # 1) Get the code
  - checkout: self

  # 2) Login via UMI and export OpenAI vars (we assume az & jq already present)
  - bash: |
      bash scripts/apply-security-config.sh --openaiModel=o3-mini
    displayName: Apply OpenAI Config

  # 3) Pull in a Python runtime (here, any 3.x)
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'    # grab the latest available 3.x
      addToPath: true       # make `python` & `pip` available on PATH

  # 4) Create a venv and install your dependencies
  - bash: |
      python -m venv .venv          # carve out an isolated env
      source .venv/bin/activate     # activate it
      pip install --upgrade pip     # ensure latest pip
      pip install -r requirements.txt
    displayName: Setup Python & Install Requirements

  # 5) Run your PR‐check (inside the same venv)
  - bash: |
      source .venv/bin/activate
      python scripts/run-pr-check.py
    displayName: Run PR Check
