# azure-pipelines.yml
# Only run on PRs against fasttrack/abadawi/test/3.0,
# and only when a .spec or .patch file changes.
trigger: none

pr:
  branches:
    include:
      - fasttrack/abadawi/test/3.0
  paths:
    include:
      - '**/*.spec'
      - '**/*.patch'

name: Automaton-OpenAI-PR-Check

pool:
  name: mariner-dev-build-1es-mariner2-amd64

steps:
  # 1) Pull down your GitHub code
  - checkout: self

  # 2) Debug: show exactly what files we have (optional)
  - task: Bash@3
    displayName: '🔍 Debug: list workspace contents'
    inputs:
      targetType: inline
      script: |
        echo "Working directory: $(pwd)"
        ls -R .

  # 3) Apply OpenAI config via your UMI login script
  - task: Bash@3
    displayName: '⚙️  Apply OpenAI Config'
    inputs:
      targetType: filePath
      filePath: 'prchecks/CveSpecFilePRCheck/apply-security-config.sh'
      arguments: '--openaiModel=o3-mini'

  # 4) Bring in a Python runtime
  - task: UsePythonVersion@0
    displayName: '🐍 Select Python 3.x'
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # 5) Run your PR-check entrypoint (which installs deps & calls Azure OpenAI)
  - task: Bash@3
    displayName: '🔍 Run PR Check'
    inputs:
      targetType: inline
      script: |
        cd prchecks/CveSpecFilePRCheck
        chmod +x ./run-pr-check.sh
        ./run-pr-check.sh
