trigger: none

pr:
  branches:
    include:
      - fasttrack

name: Automaton-OpenAI-PR-Check

pool:
  name: mariner-dev-build-1es-mariner2-amd64

variables:
  AZURE_SUBSCRIPTION_ID: '<YOUR_SUBSCRIPTION_ID>'            # in ADO UI
  YOUR_USER_ASSIGNED_IDENTITY_CLIENT_ID: '<YOUR_UMI_CLIENT_ID>'  # in ADO UI
  PYTHON_VERSION: '3.9'

steps:
- checkout: self

# install jq so our script can parse JSON
- task: Bash@3
  displayName: 'Install jq'
  inputs:
    targetType: inline
    script: |
      apt-get update && apt-get install -y jq

# render the JSON template (inject only the UMI)
- task: Bash@3
  displayName: 'Render security-config'
  inputs:
    targetType: inline
    script: |
      envsubst < scripts/security-config-dev.template.json \
        > scripts/security-config-dev.json
  env:
    umiId: $(YOUR_USER_ASSIGNED_IDENTITY_CLIENT_ID)

# now call the script—which will do the UMI login + extract OpenAI vars
- task: Bash@3
  displayName: 'Apply OpenAI Config'
  inputs:
    targetType: inline
    script: |
      bash scripts/apply-security-config.sh \
        --aiCvePatching \
        --openaiModel=o3-mini

- task: UsePythonVersion@0
  displayName: 'Select Python $(PYTHON_VERSION)'
  inputs:
    versionSpec: '$(PYTHON_VERSION)'

- task: Bash@3
  displayName: 'Install Python Dependencies'
  inputs:
    targetType: inline
    script: |
      pip install --upgrade pip
      pip install -r requirements.txt

- task: Bash@3
  displayName: 'Full PR Check (bash wrapper)'
  inputs:
    targetType: 'inline'
    script: |
      bash scripts/run-pr-check.sh
