# prchecks/CveSpecFilePRCheck/CveSpecFilePRCheck.yml
# Trigger on PRs to fasttrack/abadawi/test/3.0 when .spec or .patch files change
trigger: none

pr:
  branches:
    include:
      - fasttrack/abadawi/test/3.0
  paths:
    include:
    - '/SPECS/**/*.spec'
    - '/SPECS/**/*.patch'
    - '/SPECS-EXTENDED/**/*.spec'
    - '/SPECS-EXTENDED/**/*.patch'
    - '/SPECS-SIGNED/**/*.spec'
    - '/SPECS-SIGNED/**/*.patch'

name: Automaton-OpenAI-PR-Check

pool:
  name: mariner-dev-build-1es-mariner2-amd64

steps:
  # 1) Clone the repo
  - checkout: self

  # 2) Debug workspace (optional — remove once paths are correct)
  - task: Bash@3
    displayName: '🔍 Debug: list workspace contents'
    inputs:
      targetType: inline
      script: |
        echo "Working directory: $(pwd)"
        ls -la .
        ls -la .pipelines/prchecks/CveSpecFilePRCheck || echo "Directory not found"

  # 3) Apply OpenAI config via your UMI-login script
  - task: Bash@3
    displayName: '⚙️  Apply OpenAI Config'
    inputs:
      targetType: inline
      script: |
        # make sure we're in the folder containing the scripts
        cd .pipelines/prchecks/CveSpecFilePRCheck

        # fail fast if the script is missing
        if [ ! -f apply-security-config.sh ]; then
          echo "❌ Cannot find apply-security-config.sh in $(pwd)"
          exit 1
        fi

        # run the UMI-login + var-export script
        bash apply-security-config.sh --openaiModel=o3-mini

  # 4) Verify and use system Python
  - task: Bash@3
    displayName: '🐍 Verify System Python'
    inputs:
      targetType: inline
      script: |
        python3 --version
        which python3
        echo "Using system Python instead of downloading version"

  # 5) Run your PR‐check entrypoint (installs deps & invokes Azure OpenAI)
  - task: Bash@3
    displayName: '🔍 Run PR Check'
    inputs:
      targetType: inline
      script: |
        cd .pipelines/prchecks/CveSpecFilePRCheck
        chmod +x run-pr-check.sh
        ./run-pr-check.sh
